### ISSUE TITLE
No way to reflect schema's ReadWrite properties as ReadOnly in dictionary

### ISSUE THREAD

**Issue by ahrytsen** [DMTF/RDE-Dictionary#26]
Hi,

My device doesn't support Writes for some of properties which appears in schema profile as a ReadWrite.
To generate a dictionary I'am using a profile where I'm specifying those properties with only ReadRequirements as mandatory,
but in dictionary they appears as ReadWrite ones.
Is there a way to reflect such properties as ReadOnly in dictionary? 
If no, then is it a script issue or "Redfish Interoperability Profiles"(DSP0272) spec issue?

**Comment by J2Hilland** [comment]
I think the easiest way is to just modify the schema files that you are using as input to the dictionary.  These should probably be the same ones that are referenced and/or provided for your product anyway (this is allowed according to the Redfish spec) and are at the location given by the GetSchemaURI command.
That being said, I don't think you have to modify the dictionary.  I believe it is also legal to use the standard dictionary and then the RDE Provider would return an error if someone attempts a write (the MC doesn't have to be the one to enforce the read only rule - the provider can do it instead).

**Comment by ahrytsen** [comment]
@J2Hilland thanks for you response, sounds valid. Probably I will choose last option.
