### ISSUE TITLE
Script is not able to decode/encode correctly annotation set with child properties

### ISSUE THREAD

**Issue by ahrytsen** [DMTF/RDE-Dictionary#33]
Annotation set's properties should not have annotation selector bit, since annotations also can be annotated. (yes, sounds tricky)
For example:
```
"@Redfish.Settings" : {
    "SettingsObject" : {
        "@odata.id" : "..."
    }
}
```
So here only "@Redfish.Settings" and "@odata.id" must have annotation dictionary selector bit, since they are from root of the dictionary. In other words only properties from root of annotation dictionary(those have '@' sign) should have annot selector bit 1.

**Comment by bnatrajan** [comment]
@ahrytsen, 
This issue will be addressed in RDE 1.1 with the addition of a bit to indicate a top-level annotation during the encode process.

**Comment by ahrytsen** [comment]
Hi @bnatrajan,
For me it doesn't look like a spec issue.
Can you provide any example why we may need this additional bit?(I don't see any reason).
Annotation's child properties can't be from any other dictionary.
But only top level annotation properties should have this bit as 1.

**Comment by billschererhpe** [comment]
Anything being decoded from the annotation dictionary should have the annotation bit set.  To introduce a nested annotation you need a way to differentiate that it's a new top-level annotation; that is precisely what the new flag in RDE 1.1 does.

**Comment by ahrytsen** [comment]
@billschererhpe 
I believe it is worth to discuss this bit more if there is a chance not to add this additional flag and save backward compatibility and make our lives bit simpler.

> Anything being decoded from the annotation dictionary should have the annotation bit set.

So I think it is a root cause and I mostly not agree with this, because
all nested to top level annotation properties can be ONLY from annotation dictionary, correct me if I am wrong,
so we need to differentiate only top level annotations by this bit in order to change decoding/encoding context.
And looks better to describe this in spec than introduce new flag which can brake backward compatibility.

There is a special case when you need to annotate the nested properties with top level annotation for example:
```
{
   "@Redfish.CollectionCapabilities": { -> has annotation dict bit(since it is top level)
      "Capabilities": [ -> has not annotation dict bit, since only properties from annotation dict can be nested to the top level annotation, and decoder don’t need to change any decoding context
         {
            "CapabilitiesObject": { has not annotation dict bit, same reason
                “@odata.id”: “some link”  -> has annotation dict bit(since it is top level), decoder need to switch context to the root of annotation dictionary 
            }
         }
      ]
   }
}
```

**Comment by billschererhpe** [comment]
The proposal breaks backward compatibility with the RDE 1.0 spec and is therefore a non-starter.
