### ISSUE TITLE
generate_dictionaries hard-codes annotations schema to v1_0_0

### ISSUE THREAD

**Issue by jautor** [DMTF/RDE-Dictionary#55]
The annotations schema is currently at v1_1_0 / v1_1_1, but the folder-based script hard-codes the "redfish-payload-annotations" version to "v1_0_0".  

The script should either allow that value to be configurable, or, since these are backward compatible, just use the highest-version / latest annotations schema.  Also suggesting to the DMTF that a "redfish-payload-annotations-v1.json" file be created to always reflect the latest version to avoid these ties - as was done for the "redfish-schema-v1" schema extensions file.

**Comment by mraineri** [comment]
Fixed in latest update to reference a "v1" file instead of a specific version
